#!/bin/bash -l
#SBATCH --array=0-9
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --account=def-ekarimi
# Standard output and error:
#SBATCH -o ./jobfiles/out.%j
#SBATCH -e ./jobfiles/err.%j
#SBATCH -D ./
#SBATCH -J datagen40M4

# memory
#SBATCH --mem=30GB
#SBATCH --time=100:00:00

module load python/3.9
module load scipy-stack
source venv/bin/activate

srun python datagen.py $SLURM_ARRAY_TASK_ID