#!/bin/bash -l
#SBATCH --array=0
#SBATCH --nodes=1
#SBATCH --gpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --account=def-ekarimi
# Standard output and error:
#SBATCH -o ./datasetAna/out.%j
#SBATCH -e ./datasetAna/err.%j
#SBATCH -D ./
#SBATCH -J analyzeData

# memory
#SBATCH --mem=80GB
#SBATCH --time=165:00:00

module load python/3.9
module load scipy-stack
source venv/bin/activate

srun python analyzedataset.py 



