state: '000000+111111'
num_of_examples: 10000000
learnRate: '1.e-4'
num_of_examples_fixed:
num_of_epochs: 30000
layer_indices:
  - 2
neuron_index_set: 1
nnType: 3
modelname: '6partGHZ_seed8686.pt'
start_graph: 'best'
layer: 10
neuron: 0