state: '000000+111111'
dim: '[2] * 4'
num_of_examples: 500000 #if done in parallel, this is multiplied by the number of jobs
file_name: 'discrete_4q_10M'
file_type: 'csv' #choose between csv and pkl
discretize: True