#!/bin/bash -l
#SBATCH --partition=gpu
#SBATCH --array=0-9
#SBATCH --gres=gpu:1           # specify number of GPUs
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1

# Standard output and error:
#SBATCH -o ./jobfiles/out.%j
#SBATCH -e ./jobfiles/err.%j
#SBATCH -D ./
#SBATCH -J dream


# memory
#SBATCH --mem=180GB
#SBATCH --time=165:00:00


source venv/bin/activate
srun python dream.py $SLURM_ARRAY_TASK_ID