#!/bin/bash -l
#SBATCH --array=0-9
# Standard output and error:
#SBATCH -o ./jobfiles/out.%j
#SBATCH -e ./jobfiles/err.%j
#SBATCH -D ./
#SBATCH -J datagen
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
# memory
#SBATCH --mem=30GB
#SBATCH --time=100:00:00


source venv/bin/activate
srun python datagen.py 1