batch_size: 10000
datafile: cont_20M_2.csv
epochLRUpdate: 25
epochToSaturate: 99999
isL2Reg: false
l2Lambda: 1.0e-05
learnRate: '1.e-3'
learnRateFactor: 1.0
model_prefix: 4q_100
nnType: 2
num_of_examples: 3.e6
plotFolder: plots/100_cont
seed: 1821
showFigure: true
state: 0000+1111
zeroInput: false
