state: '000000+111111'

num_of_examples: '1.e6'
learnRate: '1.e-3'
model_prefix: '6q_cont_type13_zero'
l2Lambda: 0.00001
isL2Reg: False
nnType: 13
batch_size: 10000
datafile: 'distcont_6q_1M.csv'
zeroInput: True
showFigure: True
plotFolder: 'plots/type13_6q_zero'
epochToSaturate: 200