state: '000000+111111'
dim: '[2] * 6'
num_of_examples: 5000000 #if done in parallel, this is multiplied by the number of jobs
file_name: 'distcont_6q_20M'
file_type: 'csv' #choose between csv and pkl
discretize: 'True'