state: '0000+1111'
num_of_examples: 1000000
learnRate: '1.e-4'
num_of_examples_fixed:
num_of_epochs: 30000
nnType: 12
modelname: '4q_cont_type_12_seed1236.pt'
start_graph: 'random'
neuron_array: '[[ii,jj] for ii in [0,2,4] for jj in range(20)]' # The length of this array will determine the number of jobs you should run. 
num_start_graphs: 1
dream_file: 'dreamfiles/dream4qnrand_intermediate_type12'
datafile: 'distcont_4q_1M.csv'
bestExamples: True
seed: 888