state: '000000+111111'
num_of_examples: 1000000
learnRate: '1.e-4'
num_of_examples_fixed: 10000
num_of_epochs: 30000
nnType: 13
modelname: '6q_cont_type13_seed8978.pt'
start_graph: 'random'
neuron_array: '[[10,0]]' # The length of this array will determine the number of jobs you should run. 
num_start_graphs: 100
dream_file: 'dreamfiles/dream6qnrand_output_type13'
datafile: 'distcont_6q_1M.csv'
bestExamples: False
seed: 888