state: '000000+111111'

num_of_examples: '1.e7'
learnRate: '1.e-3'
model_prefix: '6q_cont_type7'
l2Lambda: 0.00001
isL2Reg: False
nnType: 7
batch_size: 10000
datafile: 'cont_6q_10M.csv'
seed: 111
zeroInput: False
showFigure: True
epochToSaturate: 200