state: '0000+1111'
dim: '[2] * 4'
num_of_examples: 3000000 #if done in parallel, this is multiplied by the number of jobs
file_name: 'distcont_4q_6M'
file_type: 'csv' #choose between csv and pkl
discretize: 'False'