state: '000000+111111'
num_of_examples: 1.0e6
learnRate: '1.e-4'
num_of_examples_fixed: 10000
num_of_epochs: 30000
nnType: 13
modelname: '6q_cont_type13_20M_seed8875.pt'
start_graph: 'random'
neuron_array: '[[0,ii] for ii in range(0,50,5)] + [[2,ii] for ii in range(0,40,4)] + [[4,ii] for ii in range(0,30,3)] + [[6,ii] for ii in range(0,20,2)] + [[8,ii] for ii in range(0,10,1)]' 
num_start_graphs: 10
dream_file: 'dreamfiles/dream6qnrand_type13'
datafile: 'distcont_6q_1M.csv'
bestExamples: True
seed: 888