state: '0000+1111'
num_of_examples: 10000000
learnRate: '1.e-4'
num_of_examples_fixed:
num_of_epochs: 30000
nnType: 4
modelname: '4q_discrete_seed111.pt'
start_graph: 'random'
neuron_array: '[[14,0]]'
num_start_graphs: 100
dream_file: 'dreamfiles/discrete_4q_10M.csv'
datafile: 'discrete_4q_10M.csv'
seed: 999