state: '000000+111111'
num_of_examples: 10000000
learnRate: '1.e-4'
num_of_examples_fixed:
num_of_epochs: 30000
nnType: 5
modelname: '6partGHZ_seed111.pt'
start_graph: 'zero'
neuron_array: '[[12,i] for i in range(20)]'
num_start_graphs: 1
dream_file: 'dreamfiles/dream6q20nzero'
datafile: 'data_train.pkl'
seed: 888