state: '0000+1111'
num_of_examples: 1.e6
learnRate: '1.e-3'
num_of_examples_fixed: 1000
num_of_epochs: 100000
nnType: 1
modelname: 'GHZFidelity_400.pt'
start_graph: 'random'
neuron_array: '[[8,0]]'   
num_start_graphs: 10
dream_file: 'dreamfiles/test'
datafile: 'cont_4q_1M.csv'
bestExamples: False
seed: 888
useGrad: True
learnRateFactor: 1.0
epochLRUpdate: 99999
L1Alpha: 0.000
prop: 'fidelity'



