state: '0000+1111'

num_of_examples: '2.e7'
learnRate: '1.e-3'
model_prefix: '4q_cont_type15_20M_3'
l2Lambda: 0.00001
isL2Reg: False
nnType: 15
batch_size: 10000
datafile: 'distcont_4q_20M.csv'
zeroInput: False
showFigure: True
plotFolder: 'plots/type15_4q_20M_3'
epochToSaturate: 99999
learnRateFactor: 0.8
epochLRUpdate: 100

