state: '0000+1111'

num_of_examples: '2.e7'
learnRate: '1.e-3'
model_prefix: '4q_400'
l2Lambda: 0.00001
isL2Reg: False
nnType: 1
batch_size: 10000
datafile: 'cont_20M.csv'
zeroInput: False
showFigure: True
plotFolder: 'plots/400_cont_2'
epochToSaturate: 99999
learnRateFactor: 1.0
epochLRUpdate: 25
